version: '3.0'
services:
  apache-php:
    build: ./apache-php
    ports:
      - 8080:8080
    environment:
      PHP_SMTP: localhost
      PHP_SMTP_FROM: TULIO
    volumes:
      - ./apache-php/html:/home/www/html
      


